
name: Overwatch-Server-Selector

on: 
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: gh_checkout
        uses: actions/checkout@v4
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
      - name: exe_to_workflow
        uses: actions/upload-artifact@v4
        with:
          name: MINA Overwatch 2 Server Selector.exe
          path: dist
      - name: gh_tag
        id: gh_tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: gh_release
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request'}}
        with:
          files: dist/windows/MINA Overwatch 2 Server Selector.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.gh_tag.outputs.tag }}

